name: Code Coverage

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - 1.*
      - 2.*

jobs:
  coverage:
    uses: mrgoodbytes8667/workflows/.github/workflows/code-coverage.yml@php8.2-8.3
    secrets: inherit
    with:
      phpUnitVersion: 9.6